import { faSun, faCloudSun, faCloud, faCloudRain, faCloudShowersHeavy, faSnowflake, faCloudBolt } from "@fortawesome/free-solid-svg-icons"

export const WEATHER_CODE_NAMES = new Map()
export const WEATHER_CODE_ICONS = new Map()

WEATHER_CODE_NAMES
  .set(0, "ensolarado")
  .set(1, "parcialmente ensolarado")
  .set(2, "parcialmente nublado")
  .set(3, "nublado")
  .set(45, "neblina")
  .set(48, "neblina")
  .set(51, "chuvisco leve")
  .set(52, "chuvisco moderada")
  .set(55, "chuvisco densa")
  .set(56, "chuvisco frio e leve")
  .set(57, "chuvisco frio e densa")
  .set(61, "chuvas leves")
  .set(63, "chuvas moderadas")
  .set(65, "chuvas intensas")
  .set(66, "chuva gelada e leve")
  .set(67, "chuva gelada e intensa")
  .set(71, "nevasca leve")
  .set(73, "nevasca moderada")
  .set(75, "nevasca intensa")
  .set(77, "chuva de granizo")
  .set(80, "pancadas de chuva leve")
  .set(81, "pancadas de chuva moderada")
  .set(82, "pancadas de chuva intensa")
  .set(85, "pancadas de neve leves")
  .set(86, "pancadas de neve intensas")
  .set(95, "tempestade de trovão")
  .set(96, "tempestade com chuvas leves")
  .set(99, "tempestade com chuvas fortes")

WEATHER_CODE_ICONS
  .set(0, faSun)
  .set(1, faCloudSun)
  .set(2, faCloud)
  .set(3, faCloud)
  .set(45, faCloud)
  .set(48, faCloud)
  .set(51, faCloudRain)
  .set(52, faCloudRain)
  .set(55, faCloudRain)
  .set(56, faCloudRain)
  .set(57, faCloudRain)
  .set(61, faCloudShowersHeavy)
  .set(63, faCloudShowersHeavy)
  .set(65, faCloudShowersHeavy)
  .set(66, faCloudShowersHeavy)
  .set(67, faCloudShowersHeavy)
  .set(71, faSnowflake)
  .set(73, faSnowflake)
  .set(75, faSnowflake)
  .set(77, faSnowflake)
  .set(80, faCloudShowersHeavy)
  .set(81, faCloudShowersHeavy)
  .set(82, faCloudShowersHeavy)
  .set(85, faSnowflake)
  .set(86, faSnowflake)
  .set(95, faCloudBolt)
  .set(96, faCloudBolt)
  .set(99, faCloudBolt)